PLUGIN_NAME=        opnsense-auth-oidc
PLUGIN_VERSION=     0.1
PLUGIN_COMMENT=     OPNsense interactive OpenID Connect authentication backend
PLUGIN_MAINTAINER=  you@example.com
PLUGIN_DEVEL=       yes

.include "../.mk"
