PLUGIN_NAME=        os-oidc
PLUGIN_VERSION=     0.1
PLUGIN_COMMENT=     Interactive OpenID Connect authentication backend (Authorization Code + PKCE)
PLUGIN_MAINTAINER=  you@example.com
PLUGIN_DEVEL=       yes

.include "../.mk"
